AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Parameters:
  DBHOST:
    Type: String
    Description: The database host (RDS Endpoint)
  DBUSER:
    Type: String
    Description: The database user
  DBPASS:
    Type: String
    NoEcho: true
    Description: The database password
  DBNAME:
    Type: String
    Description: The database name
Resources:
  CreateContactFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/create.handler
      Runtime: nodejs18.x
      Events:
        CreateApi:
          Type: Api
          Properties:
            Path: /contacts
            Method: POST
      MemorySize: 128
      Timeout: 20
      Environment:
        Variables:
          DB_HOST: !Ref DBHOST
          DB_USER: !Ref DBUSER
          DB_PASS: !Ref DBPASS
          DB_NAME: !Ref DBNAME
      VpcConfig:
        SubnetIds:
          - subnet-0db8341112d35815d
          - subnet-044f5e62d787161bf
        SecurityGroupIds:
          - sg-070d584622d5d9f4b

  ReadContactsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/read.handler
      Runtime: nodejs18.x
      Events:
        ReadApi:
          Type: Api
          Properties:
            Path: /contacts
            Method: GET
      MemorySize: 128
      Timeout: 20
      Environment:
        Variables:
          DB_HOST: !Ref DBHOST
          DB_USER: !Ref DBUSER
          DB_PASS: !Ref DBPASS
          DB_NAME: !Ref DBNAME
      VpcConfig:
        SubnetIds:
          - subnet-0db8341112d35815d
          - subnet-044f5e62d787161bf
        SecurityGroupIds:
          - sg-070d584622d5d9f4b

  UpdateContactFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/update.handler
      Runtime: nodejs18.x
      Events:
        UpdateApi:
          Type: Api
          Properties:
            Path: /contacts
            Method: PUT
      MemorySize: 128
      Timeout: 20
      Environment:
        Variables:
          DB_HOST: !Ref DBHOST
          DB_USER: !Ref DBUSER
          DB_PASS: !Ref DBPASS
          DB_NAME: !Ref DBNAME
      VpcConfig:
        SubnetIds:
          - subnet-0db8341112d35815d
          - subnet-044f5e62d787161bf
        SecurityGroupIds:
          - sg-070d584622d5d9f4b

  DeleteContactFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/delete.handler
      Runtime: nodejs18.x
      Events:
        DeleteApi:
          Type: Api
          Properties:
            Path: /contacts
            Method: DELETE
      MemorySize: 128
      Timeout: 20
      Environment:
        Variables:
          DB_HOST: !Ref DBHOST
          DB_USER: !Ref DBUSER
          DB_PASS: !Ref DBPASS
          DB_NAME: !Ref DBNAME
      VpcConfig:
        SubnetIds:
          - subnet-0db8341112d35815d
          - subnet-044f5e62d787161bf
        SecurityGroupIds:
          - sg-070d584622d5d9f4b

