AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Parameters:
  DB_HOST:
    Type: String
    Description: The database host (RDS Endpoint)
  DB_USER:
    Type: String
    Description: The database user
  DB_PASS:
    Type: String
    NoEcho: true
    Description: The database password
  DB_NAME:
    Type: String
    Description: The database name
Resources:
  MyApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handler.handler
      Runtime: nodejs18.x
      CodeUri: .
      MemorySize: 128
      Timeout: 20
      Environment:
        Variables:
          DB_HOST: !Ref DB_HOST
          DB_USER: !Ref DB_USER
          DB_PASS: !Ref DB_PASS
          DB_NAME: !Ref DB_NAME
      VpcConfig:
        SubnetIds:
          - subnet-0db8341112d35815d
          - subnet-044f5e62d787161bf
        SecurityGroupIds:
          - sg-070d584622d5d9f4b
      Events:
        Api:
          Type: Api
          Properties:
            Path: /time
            Method: get
